[workspace]
authors = ["miitarou <miitarou@miitarou.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "three-body-sim"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.2.0.dev2026012405,<0.27"
numpy = ">=2.4.1,<3"
vispy = ">=0.16.1,<0.17"
